#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index_front_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

form_login:
    path: /user/create
    controller: App\Controller\UserController::create

form_logout:
    path: /user
    controller: App\Controller\UserController::index

account_register:
    path:     /register
    defaults: { _controller: AcmeAccountBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AcmeAccountBundle:Account:create }